### ISSUE TITLE
profiling report

### ISSUE THREAD

**Issue by sheffien** [ComputationalEpigenetics/pypiper#6]
Pypiper could produce a profiling report, Pipeline_profile.txt. It would include:

A single line for each subprocess that is run, detailing:
- elapsed time
- peak memory used

Also, this could indicate elapsed time between each timestamp.

Implementation: when a subprocess is running, add a variable tracking local max mem use, and elapsed time. When a each subprocess completes, write a line to the report indicating.

Also a killed child process should write the elapsed time and max memory even if it didn't complete. 

Such a report would make it easy to identify the most time-consuming and memory-consuming steps of a pipeline for optimization. anyone interested?

**Comment by jklughammer** [comment]
Done with commit 2cf7579e36d83a6da7a3a134d305d22c23a54615
